import React from 'react';
import pkg from 'react-katex';
const { BlockMath, InlineMath } = pkg;

export default function FbmSimulator() {
	return (
		<div className="mt-4 border-t border-zinc-800 pt-4">
			<h5 className="text-base font-semibold text-zinc-100">
				C++ Engine: Methodology & Implementation
			</h5>
			<div className="mt-4 space-y-4 text-sm text-zinc-400">
				<p>
					The underlying Monte Carlo engine is a high-performance C++ application designed for pricing
					derivatives under rough stochastic volatility models, such as the Rough Bergomi model. It
					leverages fractional Brownian motion (fBM) to capture empirically observed volatility dynamics.
				</p>
				<div>
					<h6 className="font-semibold text-zinc-300">Coupled SDE System</h6>
					<p>
						The engine simulates the coupled Stochastic Differential Equations for the asset price{' '}
						<InlineMath math={"S_t"} /> and its variance <InlineMath math={"V_t"} />:
					</p>
					<BlockMath math={"dS_t = \\mu S_t dt + \\sqrt{V_t} S_t dW_t^1"} />
					<BlockMath math={"V_t = V_0 \\exp\\left( \\eta B_H(t) - \\frac{1}{2} \\eta^2 t^{2H} \\right)"} />
				</div>
				<div>
					<h6 className="font-semibold text-zinc-300">fBM Simulation for H &lt; 0.5</h6>
					<p>
						Simulating the fractional Brownian motion <InlineMath math={"B_H(t)"} /> for a Hurst parameter{' '}
						<InlineMath math={"H < 0.5"} /> requires careful consideration of its auto-covariance structure. The
						covariance matrix <InlineMath math={"\\Sigma"} /> for a time grid{' '}
						<InlineMath math={"t_1, t_2, \\dots, t_n"} /> is given by:
					</p>
					<BlockMath
						math={
							"\\Sigma_{ij} = \\mathbb{E}[B_H(t_i)B_H(t_j)] = \\frac{1}{2}(t_i^{2H} + t_j^{2H} - |t_i - t_j|^{2H})"
						}
					/>
					<p className="mt-2">
						To generate valid paths, the engine performs an exact Cholesky decomposition of this dense
						covariance matrix, <InlineMath math={"\\Sigma = LL^T"} />. Correlated random variates are then
						generated by transforming a vector of independent standard normal variables{' '}
						<InlineMath math={"Z"} /> via <InlineMath math={"X = LZ"} />. This method is computationally
						intensive but ensures the statistical integrity of the generated rough volatility paths.
					</p>
				</div>
			</div>
		</div>
	);
}
